import pxljam.TheLegend27;
import renderer.Renderer;
import processing.core.PApplet;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Renderer {

    public App(){
        super(new TheLegend27());
    }

    public static void main(String[] args) {
        PApplet.main("App");
    }
}
