import core.Game;
import processing.core.PApplet;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App extends Game {
    public static void main(String[] args) {
        PApplet.main("App");
    }

}
