package util;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class LevelGenerator {

    private static final String ROOT = "./tmp"; // Root folder for level images
    private static final int MAX_SIZE = 100; // Max level grid size

    // GameEntity colours
    private static final Color PLAYER = new Color(100,0,0);
    private static final Color PLATFORM = new Color(0,0,0);
    private static final Color FAKEPLATFORM = new Color(0,0,0);
    private static final Color MOVINGPLATFORM = new Color(0,0,0);
    private static final Color FLAG = new Color(0,0,0);
    private static final Color COIN = new Color(0,0,0);
    private static final Color GHOST = new Color(0,0,0);
    private static final Color BEE = new Color(0,0,0);
    private static final Color BARNACLE = new Color(0,0,0);
    private static final Color SNAKE = new Color(0,0,0);
    private static final Color SLIME = new Color(0,0,0);


    public static String imgToLevel(String filename) throws IOException{
        // Read image
        BufferedImage img = ImageIO.read(new File(ROOT + "/tmp.png")); //TODO file selection
        if (img.getWidth() > MAX_SIZE || img.getHeight() > MAX_SIZE)
            throw new IllegalArgumentException("Image too large (" + MAX_SIZE + "x" + MAX_SIZE + ")");

        // Convert to 2D Color array
        Color[][] rgbTable = convertToArray(img);

        // Convert to level declaration
        StringBuilder level = new StringBuilder();
        level.append(header(filename));


        return null;
    }

    private static String header(String levelName) {
        return "package ivara.scenes;\n\n\n"
                + "import core.struct.Camera;\n"
                + "import core.struct.ResourceID;\n"
                + "import core.struct.Text;\n"
                + "import ivara.entities.PlatformEntity;\n"
                + "import ivara.entities.PlayerEntity;\n"
                + "import ivara.entities.*;\n"
                + "import ivara.entities.enemies.*;\n"
                + "import maths.Vector;\n\n"
                + "/**\n"
                + " * Auto-generated by LevelGenerator - Will Pearson.\n"
                + " */\n"
                + "public class " + levelName + " extends DefaultScene {\n"
                + "\tpublic void startScene(){\n";
    }

    private static Color[][] convertToArray(BufferedImage img) {
        Color[][] arr = new Color[img.getWidth()][img.getHeight()];
        for (int y = 0; y < arr.length; y++)
            for (int x = 0; x < arr[0].length; x++) {
                Color col = new Color(img.getRGB(x, y), true);
                arr[y][x] = col.getAlpha() == 0 ? null : col; // transparent pixels treated as invisible
            }
        return arr;
    }

    public static void main(String[] args) {
        try {
            imgToLevel("tmp.png");
        } catch (IOException e) {}

    }
}
