package ivara.scenes;


import core.scene.Scene;
import core.struct.Camera;
import core.struct.ResourceID;
import core.struct.Text;
import ivara.entities.PlatformEntity;
import ivara.entities.PlayerEntity;
import ivara.entities.*;
import ivara.entities.enemies.*;
import maths.Vector;

/**
 * Auto-generated by LevelGenerator - Will Pearson.
 */
public class HardLevel3 extends DefaultScene {
	public void startScene(){

		// Player
		PlayerEntity player = new PlayerEntity(19,30.5f);
		addEntity(player);

		// Checkpoints
		addEntity(new CheckpointEntity(26, 30));
		addEntity(new CheckpointEntity(32, 30));

		// Flag
		addEntity(new LevelEndEntity(37, 31));

		// Platforms
		addEntity(new PlatformEntity(new Vector(0,0),37,false));
		addEntity(new PlatformEntity(new Vector(0,1),44,true));
		addEntity(new PlatformEntity(new Vector(36,1),23,true));
		addEntity(new PlatformEntity(new Vector(9,5),2,true));
		addEntity(new PlatformEntity(new Vector(15,5),2,true));
		addEntity(new PlatformEntity(new Vector(21,5),2,true));
		addEntity(new PlatformEntity(new Vector(27,5),2,true));
		addEntity(new PlatformEntity(new Vector(6,6),25,false));
		addEntity(new PlatformEntity(new Vector(6,7),32,true));
		addEntity(new PlatformEntity(new Vector(30,7),17,true));
		addEntity(new PlatformEntity(new Vector(3,8),7,true));
		addEntity(new PlatformEntity(new Vector(31,11),4,false));
		addEntity(new PlatformEntity(new Vector(12,12),13,false));
		addEntity(new PlatformEntity(new Vector(12,13),20,true));
		addEntity(new PlatformEntity(new Vector(24,13),11,true));
		addEntity(new PlatformEntity(new Vector(32,17),5,false));
		addEntity(new PlatformEntity(new Vector(14,18)));
		addEntity(new PlatformEntity(new Vector(18,18),6,true));
		addEntity(new PlatformEntity(new Vector(3,19),13,true));
		addEntity(new PlatformEntity(new Vector(19,23),2,false));
		addEntity(new PlatformEntity(new Vector(22,23),5,false));
		addEntity(new PlatformEntity(new Vector(28,23),5,false));
		addEntity(new PlatformEntity(new Vector(34,23),7,false));
		addEntity(new PlatformEntity(new Vector(40,24),9,true));
		addEntity(new PlatformEntity(new Vector(10,27)));
		addEntity(new PlatformEntity(new Vector(9,28)));
		addEntity(new PlatformEntity(new Vector(8,29)));
		addEntity(new PlatformEntity(new Vector(22,30),3,true));
		addEntity(new PlatformEntity(new Vector(28,30),3,true));
		addEntity(new PlatformEntity(new Vector(34,30),3,true));
		addEntity(new PlatformEntity(new Vector(14,31),2,true));
		addEntity(new PlatformEntity(new Vector(20,31),2,true));
		addEntity(new PlatformEntity(new Vector(26,31),8,true));
		addEntity(new PlatformEntity(new Vector(32,31),14,true));
		addEntity(new PlatformEntity(new Vector(13,32),12,false));
		addEntity(new PlatformEntity(new Vector(27,32),4,false));
		addEntity(new PlatformEntity(new Vector(33,32),8,false));
		addEntity(new PlatformEntity(new Vector(3,36),3,true));
		addEntity(new PlatformEntity(new Vector(8,36)));
		addEntity(new PlatformEntity(new Vector(11,37),2,true));
		addEntity(new PlatformEntity(new Vector(7,38),20,false));
		addEntity(new PlatformEntity(new Vector(6,43),2,true));
		addEntity(new PlatformEntity(new Vector(1,44),32,false));

		// Moving Platforms
		addEntity(new PlatformEntity(new Vector(9,25),new Vector(9,12),6.5f));
		addEntity(new PlatformEntity(new Vector(13,30),new Vector(13,18),6));
		addEntity(new PlatformEntity(new Vector(7,35),new Vector(7,30),2.5f));
		addEntity(new PlatformEntity(new Vector(1,42),5,false,new Vector(1,6),18));

		// Markers
		//new Vector(1,6)
		//new Vector(9,12)
		//new Vector(13,18)
		//new Vector(7,30)

		// Fake Platforms
		addEntity(new FakeBlockEntity(new Vector(20, 9)));
		addEntity(new FakeBlockEntity(new Vector(24, 9)));
		addEntity(new FakeBlockEntity(new Vector(28, 9)));
		addEntity(new FakeBlockEntity(new Vector(17, 10)));
		addEntity(new FakeBlockEntity(new Vector(14, 11)));
		addEntity(new FakeBlockEntity(new Vector(21, 23)));
		addEntity(new FakeBlockEntity(new Vector(27, 23)));
		addEntity(new FakeBlockEntity(new Vector(33, 23)));
		addEntity(new FakeBlockEntity(new Vector(11, 26)));
		addEntity(new FakeBlockEntity(new Vector(25, 32)));
		addEntity(new FakeBlockEntity(new Vector(31, 32)));

		// Pushable Blocks
		addEntity(new PushableBlockEntity(20,22));
		addEntity(new PushableBlockEntity(22,22));
		addEntity(new PushableBlockEntity(26,22));
		addEntity(new PushableBlockEntity(28,22));
		addEntity(new PushableBlockEntity(32,22));
		addEntity(new PushableBlockEntity(34,22));

		// Coins
		addEntity(new CoinEntity(player, new Vector(9, 2), true));
		addEntity(new CoinEntity(player, new Vector(15, 2), true));
		addEntity(new CoinEntity(player, new Vector(21, 2), true));
		addEntity(new CoinEntity(player, new Vector(27, 2), true));
		addEntity(new CoinEntity(player, new Vector(28, 7), true));
		addEntity(new CoinEntity(player, new Vector(29, 7), true));
		addEntity(new CoinEntity(player, new Vector(35, 7), true));
		addEntity(new CoinEntity(player, new Vector(20, 8), true));
		addEntity(new CoinEntity(player, new Vector(24, 8), true));
		addEntity(new CoinEntity(player, new Vector(28, 8), true));
		addEntity(new CoinEntity(player, new Vector(29, 8), true));
		addEntity(new CoinEntity(player, new Vector(17, 9), true));
		addEntity(new CoinEntity(player, new Vector(29, 9), true));
		addEntity(new CoinEntity(player, new Vector(14, 10), true));
		addEntity(new CoinEntity(player, new Vector(29, 10), true));
		addEntity(new CoinEntity(player, new Vector(10, 11), true));
		addEntity(new CoinEntity(player, new Vector(31, 13), true));
		addEntity(new CoinEntity(player, new Vector(8, 14), true));
		addEntity(new CoinEntity(player, new Vector(3, 16), true));
		addEntity(new CoinEntity(player, new Vector(16, 16), true));
		addEntity(new CoinEntity(player, new Vector(3, 17), true));
		addEntity(new CoinEntity(player, new Vector(10, 17), true));
		addEntity(new CoinEntity(player, new Vector(15, 17), true));
		addEntity(new CoinEntity(player, new Vector(17, 17), true));
		addEntity(new CoinEntity(player, new Vector(8, 20), true));
		addEntity(new CoinEntity(player, new Vector(15, 20), true));
		addEntity(new CoinEntity(player, new Vector(10, 23), true));
		addEntity(new CoinEntity(player, new Vector(15, 24), true));
		addEntity(new CoinEntity(player, new Vector(10, 26), true));
		addEntity(new CoinEntity(player, new Vector(9, 27), true));
		addEntity(new CoinEntity(player, new Vector(8, 28), true));
		addEntity(new CoinEntity(player, new Vector(15, 28), true));
		addEntity(new CoinEntity(player, new Vector(3, 33), true));
		addEntity(new CoinEntity(player, new Vector(3, 34), true));
		addEntity(new CoinEntity(player, new Vector(7, 36), true));
		addEntity(new CoinEntity(player, new Vector(1, 43), true));
		addEntity(new CoinEntity(player, new Vector(2, 43), true));
		addEntity(new CoinEntity(player, new Vector(3, 43), true));
		addEntity(new CoinEntity(player, new Vector(4, 43), true));

		// Ghosts
		addEntity(new GhostEntity(new Vector(21,19), player));

		// Bees
		addEntity(new BeeEntity(new Vector(7,11), player, new Vector(0,0)));
		addEntity(new BeeEntity(new Vector(11,14), player, new Vector(0,0)));
		addEntity(new BeeEntity(new Vector(7,17), player, new Vector(0,0)));
		addEntity(new BeeEntity(new Vector(8,41), player, new Vector(0,2)));
		addEntity(new BeeEntity(new Vector(16,41), player, new Vector(0,-2)));
		addEntity(new BeeEntity(new Vector(24,41), player, new Vector(0,2)));

		// Barnacles
		addEntity(new BarnacleEntity(new Vector(9,4), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(15,4), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(21,4), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(27,4), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(1,7), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(3,7), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(1,8), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(4,8), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(5,8), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(2,10), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(2,12), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(2,14), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(4,14), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(5,14), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(3,15), BarnacleEntity.Direction.SOUTH, true));
		addEntity(new BarnacleEntity(new Vector(3,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(1,19), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(2,19), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(4,19), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(5,21), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(4,23), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(5,25), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(4,28), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(11,28), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(1,31), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(2,31), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(5,31), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(3,32), BarnacleEntity.Direction.SOUTH, true));
		addEntity(new BarnacleEntity(new Vector(3,35), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(1,36), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(4,36), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(5,36), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(7,37), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(9,37), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(10,37), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(1,38), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(4,38), BarnacleEntity.Direction.EAST, true));
		addEntity(new BarnacleEntity(new Vector(5,38), BarnacleEntity.Direction.WEST, true));
		addEntity(new BarnacleEntity(new Vector(5,43), BarnacleEntity.Direction.NORTH, true));

		// Snakes
		addEntity(new SnakeEntity(new Vector(32,9.5f)));
		addEntity(new SnakeEntity(new Vector(33,15.5f)));

		// Slimes
		addEntity(new SlimeEntity(new Vector(22,29)));
		addEntity(new SlimeEntity(new Vector(28,29)));
		addEntity(new SlimeEntity(new Vector(34,29)));

		// Default Scripts
		addEntity(new BackgroundEntity(new ResourceID("background")));
		addEntity(new DeathLineEntity(55));
		setCamera(new Camera());
		super.startScene(player);
	}
}
