package ivara.scenes;


import core.scene.Scene;
import core.struct.Camera;
import core.struct.ResourceID;
import core.struct.Text;
import ivara.entities.PlatformEntity;
import ivara.entities.PlayerEntity;
import ivara.entities.*;
import ivara.entities.enemies.*;
import maths.Vector;

/**
 * Auto-generated by LevelGenerator - Will Pearson.
 * This is the fake block level.
 */
public class Level3 extends DefaultScene {
	public void initialize(){

		// Player
		PlayerEntity player = new PlayerEntity(5,13.5f);
		addEntity(player);

		// Text
		addEntity(new BasicTextEntity(new Vector(6,12.5f), new Text(20, "These blocks look a bit funny...")));
		addEntity(new BasicTextEntity(new Vector(53,17f), new Text(20, "A productive day.")));

		// Checkpoints
		addEntity(new CheckpointEntity(24, 14));
		addEntity(new CheckpointEntity(39, 14));

		// Flag
		addEntity(new LevelEndEntity(52, 18));

		// Platforms
		addEntity(new PlatformEntity(new Vector(4,15),3,false));
		addEntity(new PlatformEntity(new Vector(21,15),7,false));
		addEntity(new PlatformEntity(new Vector(35,15),9,false));
		addEntity(new PlatformEntity(new Vector(6,16),4,true));
		addEntity(new PlatformEntity(new Vector(21,16),4,true));
		addEntity(new PlatformEntity(new Vector(43,16),4,true));
		addEntity(new PlatformEntity(new Vector(46,17),3,true));
		addEntity(new PlatformEntity(new Vector(47,18),2,true));
		addEntity(new PlatformEntity(new Vector(7,19),15,false));
		addEntity(new PlatformEntity(new Vector(44,19),10,false));

		// Fake Platforms
		addEntity(new FakeBlockEntity(new Vector(7, 15)));
		addEntity(new FakeBlockEntity(new Vector(8, 15)));
		addEntity(new FakeBlockEntity(new Vector(9, 15)));
		addEntity(new FakeBlockEntity(new Vector(10, 15)));
		addEntity(new FakeBlockEntity(new Vector(11, 15)));
		addEntity(new FakeBlockEntity(new Vector(12, 15)));
		addEntity(new FakeBlockEntity(new Vector(13, 15)));
		addEntity(new FakeBlockEntity(new Vector(14, 15)));
		addEntity(new FakeBlockEntity(new Vector(15, 15)));
		addEntity(new FakeBlockEntity(new Vector(16, 15)));
		addEntity(new FakeBlockEntity(new Vector(17, 15)));
		addEntity(new FakeBlockEntity(new Vector(18, 15)));
		addEntity(new FakeBlockEntity(new Vector(19, 15)));
		addEntity(new FakeBlockEntity(new Vector(20, 15)));
		addEntity(new FakeBlockEntity(new Vector(28, 15)));
		addEntity(new FakeBlockEntity(new Vector(30, 15)));
		addEntity(new FakeBlockEntity(new Vector(32, 15)));
		addEntity(new FakeBlockEntity(new Vector(34, 15)));
		addEntity(new FakeBlockEntity(new Vector(44, 15)));
		addEntity(new FakeBlockEntity(new Vector(45, 16)));

		// Coins
		addEntity(new CoinEntity(player, new Vector(7, 14), true));
		addEntity(new CoinEntity(player, new Vector(8, 14), true));
		addEntity(new CoinEntity(player, new Vector(9, 14), true));
		addEntity(new CoinEntity(player, new Vector(10, 14), true));
		addEntity(new CoinEntity(player, new Vector(11, 14), true));
		addEntity(new CoinEntity(player, new Vector(12, 14), true));
		addEntity(new CoinEntity(player, new Vector(13, 14), true));
		addEntity(new CoinEntity(player, new Vector(14, 14), true));
		addEntity(new CoinEntity(player, new Vector(15, 14), true));
		addEntity(new CoinEntity(player, new Vector(16, 14), true));
		addEntity(new CoinEntity(player, new Vector(17, 14), true));
		addEntity(new CoinEntity(player, new Vector(18, 14), true));
		addEntity(new CoinEntity(player, new Vector(19, 14), true));
		addEntity(new CoinEntity(player, new Vector(20, 14), true));
		addEntity(new CoinEntity(player, new Vector(27, 14), true));
		addEntity(new CoinEntity(player, new Vector(29, 14), true));
		addEntity(new CoinEntity(player, new Vector(31, 14), true));
		addEntity(new CoinEntity(player, new Vector(33, 14), true));
		addEntity(new CoinEntity(player, new Vector(35, 14), true));
		addEntity(new CoinEntity(player, new Vector(44, 16), true));
		addEntity(new CoinEntity(player, new Vector(45, 17), true));

		// Barnacles
		addEntity(new BarnacleEntity(new Vector(7,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(8,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(9,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(10,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(11,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(12,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(13,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(14,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(15,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(16,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(17,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(18,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(19,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(20,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(44,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(45,18), BarnacleEntity.Direction.NORTH, true));

		// Default Scripts
		addEntity(new BackgroundEntity(new ResourceID("background-sunset")));
		addEntity(new DeathLineEntity(42));
		setCamera(new Camera());
		super.startScene(player);
	}
}
