package ivara.scenes;


import core.scene.Scene;
import core.struct.Camera;
import core.struct.ResourceID;
import core.struct.Text;
import ivara.entities.PlatformEntity;
import ivara.entities.PlayerEntity;
import ivara.entities.*;
import ivara.entities.enemies.*;
import maths.Vector;

/**
 * Auto-generated by LevelGenerator - Will Pearson.
 */
public class Level4 extends DefaultScene {
	public void startScene(){

		// Player
		PlayerEntity player = new PlayerEntity(3,13.5f);
		addEntity(player);

		// Checkpoints
		addEntity(new CheckpointEntity(22, 14));

		// Flag
		addEntity(new LevelEndEntity(50, 14));

		// Platforms
		addEntity(new PlatformEntity(new Vector(2,15),4,false));
		addEntity(new PlatformEntity(new Vector(20,15),5,false));
		addEntity(new PlatformEntity(new Vector(30,15)));
		addEntity(new PlatformEntity(new Vector(36,15)));
		addEntity(new PlatformEntity(new Vector(42,15)));
		addEntity(new PlatformEntity(new Vector(48,15),5,false));
		addEntity(new PlatformEntity(new Vector(25,16)));
		addEntity(new PlatformEntity(new Vector(29,16)));
		addEntity(new PlatformEntity(new Vector(31,16)));
		addEntity(new PlatformEntity(new Vector(35,16)));
		addEntity(new PlatformEntity(new Vector(37,16)));
		addEntity(new PlatformEntity(new Vector(41,16)));
		addEntity(new PlatformEntity(new Vector(43,16)));
		addEntity(new PlatformEntity(new Vector(47,16)));
		addEntity(new PlatformEntity(new Vector(26,17)));
		addEntity(new PlatformEntity(new Vector(28,17)));
		addEntity(new PlatformEntity(new Vector(32,17)));
		addEntity(new PlatformEntity(new Vector(34,17)));
		addEntity(new PlatformEntity(new Vector(38,17)));
		addEntity(new PlatformEntity(new Vector(40,17)));
		addEntity(new PlatformEntity(new Vector(44,17)));
		addEntity(new PlatformEntity(new Vector(46,17)));
		addEntity(new PlatformEntity(new Vector(27,18)));
		addEntity(new PlatformEntity(new Vector(33,18)));
		addEntity(new PlatformEntity(new Vector(39,18)));
		addEntity(new PlatformEntity(new Vector(45,18)));

		// Moving Platforms
		addEntity(new PlatformEntity(new Vector(6,15),3,false,new Vector(17,15),6)); // TODO: Fill in end position and duration

		// Ghosts
		addEntity(new GhostEntity(new Vector(27,16), player));
		addEntity(new GhostEntity(new Vector(33,16), player));
		addEntity(new GhostEntity(new Vector(39,16), player));
		addEntity(new GhostEntity(new Vector(45,16), player));
		addEntity(new GhostEntity(new Vector(13,18), player));

		// Default Scripts
		addEntity(new BackgroundEntity(new ResourceID("background")));
		addEntity(new DeathLineEntity(42));
		setCamera(new Camera());
		super.startScene(player);
	}
}
