package ivara.scenes;


import core.scene.Scene;
import core.struct.Camera;
import core.struct.ResourceID;
import core.struct.Text;
import ivara.entities.PlatformEntity;
import ivara.entities.PlayerEntity;
import ivara.entities.*;
import ivara.entities.enemies.*;
import maths.Vector;

/**
 * Auto-generated by LevelGenerator - Will Pearson.
 */
public class Level3 extends DefaultScene {
	public void startScene(){

		// Player
		PlayerEntity player = new PlayerEntity(5,13.5f);
		addEntity(player);

		// Checkpoints
		addEntity(new CheckpointEntity(24, 14));

		// Platforms
		addEntity(new PlatformEntity(new Vector(4,15),3,false));
		addEntity(new PlatformEntity(new Vector(21,15),6,false));
		addEntity(new PlatformEntity(new Vector(6,16),4,true));
		addEntity(new PlatformEntity(new Vector(21,16),4,true));
		addEntity(new PlatformEntity(new Vector(7,19),15,false));

		// Fake Platforms
		addEntity(new FakeBlockEntity(new Vector(7, 15)));
		addEntity(new FakeBlockEntity(new Vector(8, 15)));
		addEntity(new FakeBlockEntity(new Vector(9, 15)));
		addEntity(new FakeBlockEntity(new Vector(10, 15)));
		addEntity(new FakeBlockEntity(new Vector(11, 15)));
		addEntity(new FakeBlockEntity(new Vector(12, 15)));
		addEntity(new FakeBlockEntity(new Vector(13, 15)));
		addEntity(new FakeBlockEntity(new Vector(14, 15)));
		addEntity(new FakeBlockEntity(new Vector(15, 15)));
		addEntity(new FakeBlockEntity(new Vector(16, 15)));
		addEntity(new FakeBlockEntity(new Vector(17, 15)));
		addEntity(new FakeBlockEntity(new Vector(18, 15)));
		addEntity(new FakeBlockEntity(new Vector(19, 15)));
		addEntity(new FakeBlockEntity(new Vector(20, 15)));

		// Barnacles
		addEntity(new BarnacleEntity(new Vector(7,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(8,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(9,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(10,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(11,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(12,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(13,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(14,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(15,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(16,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(17,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(18,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(19,18), BarnacleEntity.Direction.NORTH, true));
		addEntity(new BarnacleEntity(new Vector(20,18), BarnacleEntity.Direction.NORTH, true));

		// Default Scripts
		addEntity(new BackgroundEntity(new ResourceID("background")));
		addEntity(new DeathLineEntity(42));
		setCamera(new Camera());
		super.startScene(player);
	}
}
