package ivara.scenes;


import core.scene.Scene;
import core.struct.Camera;
import core.struct.ResourceID;
import core.struct.Text;
import ivara.entities.PlatformEntity;
import ivara.entities.PlayerEntity;
import ivara.entities.*;
import ivara.entities.enemies.*;
import maths.Vector;

/**
 * Auto-generated by LevelGenerator - Will Pearson.
 */
public class TestLevel3 extends DefaultScene {
	public void startScene(){

		// Player
		PlayerEntity player = new PlayerEntity(2,16.5f);
		addEntity(player);

		// Platforms
		addEntity(new PlatformEntity(new Vector(4,17)));
		addEntity(new PlatformEntity(new Vector(5,16)));
		addEntity(new PlatformEntity(new Vector(2,18)));
		addEntity(new PlatformEntity(new Vector(3,19)));
		addEntity(new PlatformEntity(new Vector(10,19)));
		addEntity(new PlatformEntity(new Vector(4,20)));
		addEntity(new PlatformEntity(new Vector(5,21)));
		addEntity(new PlatformEntity(new Vector(6,22)));
		addEntity(new PlatformEntity(new Vector(12,22)));
		addEntity(new PlatformEntity(new Vector(7,23),3,false));
		addEntity(new PlatformEntity(new Vector(16,23)));
		addEntity(new PlatformEntity(new Vector(10,24)));
		addEntity(new PlatformEntity(new Vector(11,25)));
		addEntity(new PlatformEntity(new Vector(19,25)));
		addEntity(new PlatformEntity(new Vector(23,25)));
		addEntity(new PlatformEntity(new Vector(12,26),5,false));
		addEntity(new PlatformEntity(new Vector(17,27)));
		addEntity(new PlatformEntity(new Vector(18,28)));
		addEntity(new PlatformEntity(new Vector(19,29),9,false));

		// Default Scripts
		addEntity(new BackgroundEntity(new ResourceID("background")));
		addEntity(new DeathLineEntity(43));
		setCamera(new Camera());
		super.startScene(player);
	}
}
